version: "3.9"

services:
  # App service
  api:
    build: .
    image: express-ts-better-sqllite3-image
    container_name: express-ts-better-sqllite3-container
    ports:
      - 5000:5000
    environment:
      - PORT=5000

    networks:
      - express-ts-better-sqllite3-network

networks:
  express-ts-better-sqllite3-network:
    name: express-ts-better-sqllite3-network
    driver: bridge
